apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-paths

spec:
  rules:
  - host: demo.juliaolkhovykdemo.tk
    http:
      paths:
      - backend:
          serviceName: demo-service
          servicePort: 80
